### ISSUE TITLE
[iOS] A crash on attempt to import KMZ

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#107]
A report by @MezAkos from Telegram Chat:

Hi! I started to test the app and I found the following issue:
1.: Convert gpx to kmz
2.: Add the converted file to OMaps
3.: Open the added bookmarks collection
4.: Delete the collection

Expected behaviour: list deletes with no errors

Actual behaviour: App crashes, but on the next opening the list is deleted

iOS 14.3 iPhone 6S

**Comment by vng** [comment]
Fixed.
