### ISSUE TITLE
[Android] A crash in the background if "Google Services" are disabled

### ISSUE THREAD

**Issue by ooprizrakoo** [omapsapp/omapsapp#110]
Omaps works fine with Google Play Services enabled.
Some user disabled them some time ago for privacy reasons. 
Omaps can work without them (that's why the app has this option in settings). When user disable them, Omaps keeps crashing and is not able to determine current location.

Omaps crashes when it's in the background.

**Comment by rtsisyk** [comment]
Postponed. 99% of users have Google Play. Let's focus on them first.

**Comment by rtsisyk** [comment]
Please try non-Google version instead.
