### ISSUE TITLE
[iOS] Fix Help screen

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#182]
<img width="626" alt="Screenshot 2021-02-20 at 23 56 52" src="https://user-images.githubusercontent.com/1799054/108608332-55d33500-73d7-11eb-956e-779f15ebb951.png">

**Comment by vng** [comment]
- Should we use dynamic help page? In that case we should make https://support.omaps.app page. Like in ./data/faq.html
- Check that ios@omaps.app, android@omaps.app are valid emails
^^ @rtsisyk @biodranik

**Comment by rtsisyk** [comment]
- Please use omaps.app/faq instead of a separate domain.
- *@omaps.app are valid domains.

**Comment by vng** [comment]
Хорошо, там будет FAQ именно по прилаге? Как в ./data/faq.html ?
