### ISSUE TITLE
[iOS] Fix About screen

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#183]
<img width="626" alt="Screenshot 2021-02-20 at 23 57 55" src="https://user-images.githubusercontent.com/1799054/108608358-86b36a00-73d7-11eb-9d6b-5540cd52c63a.png">

**Comment by vng** [comment]
https://github.com/omapsapp/omapsapp/pull/250
- Advertising is removed
- Open OMaps Twitter for all
- Register FB OMaps account

^^ @rtsisyk @biodranik
