### ISSUE TITLE
Can not clone submodules

### ISSUE THREAD

**Issue by petabyteboy** [omapsapp/omapsapp#209]
```
fatal: git cat-file: could not get object info
Unrecognized git object type:
Unable to checkout 7516753825500f90ac2de6f18c256d5abec1ff33 from https://github.com/omapsapp/just_gtfs.git.

**Comment by biodranik** [comment]
Submodule checkout issues are not related to us. Please check other possible reasons: lack of free space, bad permissions, corrupted local files, etc.
Maybe deleting 3party folder and then checking out everything again, including `git submodule update --init --recursive` help.

**Comment by biodranik** [comment]
@petabyteboy thanks! Please check if it works now.

**Comment by rtsisyk** [comment]
@biodranik I found that our submodule of just_gtfs is a little bit outdated. 

Our submodule:

```
commit 7516753825500f90ac2de6f18c256d5abec1ff33 (HEAD -> master2)
Author: Khlopkova Olga <o.khlopkova@corp.mail.ru>
Date:   Fri Feb 5 17:59:44 2021 +0300

    Fixes for StopLocationType & FareTransfers::Unlimited
```
= 5 commits from the beginning.

Upsteam repo:

```
commit 574b946dce6ee2392af91f632521633448878b75 (origin/master, origin/HEAD, master)
Merge: 46996ef f5c932d
Author: Olga Khlopkova <mesozoic.drones@gmail.com>
Date:   Wed Jan 20 14:23:22 2021 +0300

    Merge pull request #7 from tatiana-yan/master

    Parse time >= 100 hours for multi-day routes.
```

= 33 commits from the beginning


I see that 280d2aa614a1bf287eb65da082cedc19b8673cc5 commit from mapsme/omim downgraded the submodule.

Do we want to upgrade to the latest version?
