### ISSUE TITLE
Map generator for old apps (minsdk 15)

### ISSUE THREAD

**Issue by Tobey16** [omapsapp/omapsapp#294]
I tried to generate maps from the "split-repo" as there is  min sdk version 15. But i could not get the map generated. It said like Module somewhat "maps_generator.generator" could not be found. Sadly i cannot repeat that now, as i somehow run into other trouble. 
Anyone can tell me a version prior to "split-repo" that has a working maps generator?

**Comment by biodranik** [comment]
Are you trying to checkout and build from some old commit? Why do you need that? What is your use-case?

**Comment by Tobey16** [comment]
Yes! I am trying on 6302200 now.  I almost got to build an apk but then another error. See attached log.
[error build apk.txt](https://github.com/omapsapp/omapsapp/files/6257835/error.build.apk.txt)

**Comment by biodranik** [comment]
You did not install Android SDK properly. Please read your errors carefully. It is not related to OMaps.

**Comment by biodranik** [comment]
Also, if you need to build map generator, you don't need to build apk for Android.

**Comment by Tobey16** [comment]
> You did not install Android SDK properly. Please read your errors carefully. It is not related to OMaps.

You mean Ubuntu could not install it properly.
-> android-sdk is already the newest version (25.0.0+10~18.04.2).

**Comment by Tobey16** [comment]
> Also, if you need to build map generator, you don't need to build apk for Android.

If i take the effort with all of this, i take some more of it ;-)

**Comment by Tobey16** [comment]
Why is gradle checking for Android SDK Build-Tools 28.0.3 when i only got 27.0.1 installed?

**Comment by Tobey16** [comment]
I came to a solution. I had to manually download the android sdk cmdline-tools and unzip them into sdk.

I have one still one question: How can i find the version number, that the apk will have after compiling?

**Comment by biodranik** [comment]
See gradle.properties
