### ISSUE TITLE
No app / no map?

### ISSUE THREAD

**Issue by Tobey16** [omapsapp/omapsapp#64]
Can i download the apk somewhere, or do only some github users use this app?
I know a bit about programming and have programmed some simple apps and know how to program a microcontroller. But Using github and compiling a big project like this is beyond my abilitys at the moment. It would probably take me weeks to get a succesful compilation done, since i also use windows.

I would like to use this app on my 4.3 Andoid Smarphone, but i cannot download maps anymore.

It would be awesome, if someone could compile a few versions of the app and the maps generator, so others could benefit too.

**Comment by rtsisyk** [comment]
> I would like to use this app on my 4.3 Andoid Smarphone, but i cannot download maps anymore.

We have a beta version for Android in [our CI](https://github.com/omapsapp/omapsapp/actions?query=workflow%3ABeta).
Click Actions -> Beta -> Select the latest build -> Scroll down the page -> Download android-web-arm64-v8a-beta zip archive, unzip it, install apk.

![github-1](https://user-images.githubusercontent.com/1799054/103631269-d1764100-4f53-11eb-9189-424071d2481a.png)
![github-2](https://user-images.githubusercontent.com/1799054/103631264-d0451400-4f53-11eb-9d63-6c54e82d2b78.png)

You can also sign up for the closed beta program: https://appdistribution.firebase.dev/i/4fa64e2439ca20ff

**Comment by Tobey16** [comment]
This version is still to new for my smartphone it has only sdk18, and this needs sdk 21.

**Comment by Tobey16** [comment]
Also i would need the map generator with it.

**Comment by rtsisyk** [comment]
> This version is still to new for my smartphone it has only sdk18, and this needs sdk 21.

According to https://www.appbrain.com/stats/top-android-sdk-versions, Android 4.4 has 2.0% market share. I think that is buying a new phone will be cheaper than porting to SDK18 in terms of money / time spent.

**Comment by Tobey16** [comment]
Buying a new smartphone is not an option for me. This would result in a lot of work i would have to put into it. Also it may be possible, that some of them would not work anymore. It should be quite easy for some of you to generate the version i need. Also it would be good that other could have it to. There may be a lot of people that want this app / or different versions, but cant download nor build it.

**Comment by Tobey16** [comment]
I actuallly would only need the maps generator.

**Comment by rtsisyk** [comment]
> I actuallly would only need the maps generator.

https://github.com/omapsapp/omapsapp/blob/master/docs/INSTALL.md#maps-generator
