### ISSUE TITLE
iOS: disable/hide the traffic layer

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#69]
![image](https://user-images.githubusercontent.com/1799054/103650121-99312b80-4f70-11eb-92ab-6a31b9725022.png)
![image](https://user-images.githubusercontent.com/1799054/103650277-d3023200-4f70-11eb-99a7-9e62565a0799.png)

**Comment by Altonss** [comment]
Somehow the traffic layer (at least the button) is still present on the latest desktop version. Is this normal and what is it supposed to do? ping @biodranik 
Because it is not present on android, and I saw in this issue that has been removed from iOS too ...

**Comment by biodranik** [comment]
Desktop version is used for debug and development. We likely add the traffic back again when an appropriate source of it will be found.
