### ISSUE TITLE
About Documentation

### ISSUE THREAD

**Issue by MakarovMVict** [omapsapp/omapsapp#84]
Hello! I am an android application developer and I need to rewrite one application for the mapsme engine. Customers advised this fork as the original mapsme is very cumbersome and takes a long time to assemble.
Can you give me a link to detailed documentation on how your application engine works please?

**Comment by rtsisyk** [comment]
Hi @MakarovMVict ,

Thanks for your interest in this project. Unfortunately, we don't have any information regarding internals. All available documentation is stored in ["/docs"](https://github.com/omapsapp/omapsapp/tree/master/docs) folder.
