### ISSUE TITLE
Maps are outdated

### ISSUE THREAD

**Issue by dbf256** [omapsapp/omapsapp#87]
Not sure what is a date of map generation, but I don't see objects added in December.

**Comment by dbf256** [comment]
Looks like they are more than 2 month old - there is no option to edit POI in editor now.

**Comment by rtsisyk** [comment]
We plan to update maps soon.

**Comment by dbf256** [comment]
> 
> 
> We plan to update maps soon.

Thanks, outdated maps was a permanent issue with mapsme, hope it will be better with omaps.

**Comment by rtsisyk** [comment]
@vng any news?

**Comment by rtsisyk** [comment]
Fixed by 96022eb933dfe32a708baf37a1a98522077cbf3d

**Comment by dbf256** [comment]
@rtsisyk can I download version with new maps for Android somehow now?

**Comment by white-gecko** [comment]
What is the frequency for the update of the maps?
Information on the recency of the data (#816) would also help here.

**Comment by herriotto** [comment]
There is the ability to 'add a place' as in a poi etc., but I dont see the ability to provide feedback on roads, buildings, natural features or their attributes in the app. Is this anywhere on the road map to do through the app to ensure users can provide feedback on stale features or areas?

**Comment by biodranik** [comment]
Is there a list of properties you wanted to update? We plan to improve the editor, but previously it was focused on general users who doesn't know about OSM and tags.

**Comment by herriotto** [comment]
Even items for general users such as, missing roads, roads closed, non motorized or bike only roads,  to help improve general routing?

**Comment by biodranik** [comment]
That's a good idea. It would be great to have a list of such features/types that can be selected on the map, with a limited list of allowed choices so the general audience won't break the OSM data. Maybe create a note instead of the direct edit?
Or maybe we should not target a general audience at all, and instead, focus on professional OSMers. But OSMand is already very good in this area.

**Comment by dbf256** [comment]
> 
> 
> That's a good idea. It would be great to have a list of such features/types that can be selected on the map, with a limited list of allowed choices so the general audience won't break the OSM data. Maybe create a note instead of the direct edit?


There is a support of notes in organicmaps already, but it could not be used for lines (like roads) and areas as described in https://github.com/organicmaps/organicmaps/issues/266 If it is fixed it would be very helpful (now I use another app to place notes because of it).

**Comment by cayenne17** [comment]
> Quelle est la fréquence de mise à jour des cartes ? Des informations sur la récence des données ( [#816 ](https://github.com/organicmaps/organicmaps/issues/816)) seraient également utiles ici.

Hello,
I'm trying to find out how often the map is updated?

It would also be interesting to put this info somewhere in the application or in the FAQ.

**Comment by biodranik** [comment]
We mention it in the FAQ: https://github.com/organicmaps/organicmaps/blob/master/data/faq.html#L441
At the moment we update maps data approx once per month.

**Comment by NotSoImportant** [comment]
Once a month? In the app it currently tells me: "OpenStreetMap data: 14.03.2022", which is over 7 weeks ago.
Is there any (easy) way to update the maps on my own?

**Comment by biodranik** [comment]
Did you update the app to the April version?

Sometimes updates are delayed because of the found bugs or delayed code reviews. You can try to build our generator_tool and generate maps using it.

**Comment by NotSoImportant** [comment]
Thanks. After updating the app it shows a newer date in the help dialog (actually I reinstalled and all downloaded maps were gone).
I am not sure about the date of the actual map data. Does an app update also update all installed apps? Is this the only way to update maps? Or will updates e.g. show up in the map manager or do users have to reinstall outdated maps, or...?

**Comment by biodranik** [comment]
Now maps can be updated only after updating the app. Later map updates will be independent.

**Comment by cayenne17** [comment]
> Now maps can be updated only after updating the app. Later map updates will be independent.

Currently, this is still not the case, you have to update the application to have access to the map update.
